Repository Potato-Dungeon/Dungeon-crawler, pull requests merged in 2019-12, with the labels that each got.

#9 Movement overhaul
  assets/main-character.png
  js/App.js
  js/Grid.js
  js/player.js
  styles/style.css
Labels: enhancement, good first issue

#11 Movement overhaul, added testlevel, CollisionFunction
  .vscode/settings.json
  assets/coin.png
  assets/silvercoin.png
  js/App.js
  js/Coin.js
  js/Grid.js
  js/Tile.js
  js/levels.js
  js/player.js
  js/utils.js
  styles/style.css
Labels: enhancement

#12 Added basic backpack function + merging
  js/Grid.js
  js/player.js
Labels: documentation

#14 Can collect coins and added enemy
  js/Coin.js
  js/Grid.js
  js/RaisedSaint.js
  js/entity.js
  js/levels.js
  styles/style.css
Labels: enhancement

#16 Enemy overhaul + enemy fix
  .vscode/settings.json
  assets/RaisedSaintv2.png
  js/Grid.js
  js/RaisedSaint.js
  js/levels.js
  js/player.js
  styles/style.css
Labels: enhancement

#21 Implementation of soundeffects
  assets/bossInquisitor.png
  assets/sounds/applebite.wav
  assets/sounds/bossdeath.wav
  assets/sounds/bosswin.wav
  assets/sounds/enemydeath.wav
  assets/sounds/goldpickup.wav
  assets/sounds/playerdeath.wav
  assets/sounds/skeletonwalk.wav
  js/Grid.js
  js/Tile.js
  js/levels.js
Labels: Ready for Launch, enhancement
